# Generated by Django 3.1.5 on 2021-02-05 14:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_teacher', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('reference_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve_plan_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('solve_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('actual_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_photo', to='blue_chart_app.answer')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CauseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_overcome', models.BooleanField(null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connects', to='blue_chart_app.answer')),
                ('cause_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connects', to='blue_chart_app.causetag')),
                ('connect_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('page', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_problem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_similars', to='blue_chart_app.problem')),
                ('to_problem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_similars', to='blue_chart_app.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Problem_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(default='', max_length=20)),
                ('number', models.IntegerField(default=0, null=True)),
                ('page', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.section')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='blue_chart_app.problem_group'),
        ),
        migrations.CreateModel(
            name='LatestConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_connects', to='blue_chart_app.causetag')),
                ('connect_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='blue_chart_app.connect')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.problem')),
                ('solve_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='blue_chart_app.type')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_for_site_user', to=settings.AUTH_USER_MODEL)),
                ('evaluation_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_for_evalution', to='blue_chart_app.evaluationtag')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluates', to='blue_chart_app.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Develop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_develops', to='blue_chart_app.problem')),
                ('to_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_develops', to='blue_chart_app.problem')),
            ],
        ),
        migrations.AddField(
            model_name='connect',
            name='latest_connect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.latestconnect'),
        ),
        migrations.CreateModel(
            name='CommentForEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_evaluate', to='blue_chart_app.evaluate')),
            ],
        ),
        migrations.CreateModel(
            name='CommentForConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_connect', to='blue_chart_app.connect')),
            ],
        ),
        migrations.CreateModel(
            name='CommentForAnswerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_for_answer_photo', to='blue_chart_app.answerphoto')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_for_answer', to='blue_chart_app.answer')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.subject'),
        ),
        migrations.AddField(
            model_name='causetag',
            name='cause_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='blue_chart_app.type'),
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.correctsituation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_chart_app.problem'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
