# Generated by Django 3.1.5 on 2021-02-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blue_chart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_answer', to='blue_chart_app.answer'),
        ),
        migrations.AlterField(
            model_name='latestconnect',
            name='connect_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blue_chart_app.connect'),
        ),
    ]
