# Generated by Django 3.1.5 on 2021-02-11 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blue_chart_app', '0002_auto_20210211_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerphoto',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
